springdoc:
  api-docs:
    path: /swagger.json
  swagger-ui:
    enabled: true
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    shutdown:
      enabled: true